### ISSUE TITLE
Cancel Button

### ISSUE THREAD

**Issue by EclipsePlays** [iktools/Ancient-Star#35]
Something that allows you to cancel  choosing units to send to another planet. Found it as a bug, I always misclick and it's annoying.![IMG_20220129_202417.jpg](https://user-images.githubusercontent.com/85320516/151660908-0de464d8-fcde-4ba6-bee0-5620ea9dc7b5.jpg)

**Comment by iktools** [comment]
I'm not sure if you want to close fleet panel or return to the multiple selection panel so I've implemented both :). Close button is live in v2.3 and back to multiselect will be available in a few days in v2.4
