### ISSUE TITLE
Better Research Tree

### ISSUE THREAD

**Issue by EclipsePlays** [iktools/Ancient-Star#36]
Will post/comment possible research trees that could aid the player and add diversity to the game in the future.

**Comment by iktools** [comment]
There is a plan for such feature, along the lines of having them as unlocks after certain levels of tech fields is researched. But for discussions please use either [Discord](https://discord.gg/nc66tMS3ZD) or the [discussion board](https://github.com/iktools/Ancient-Star/discussions).
