### ISSUE TITLE
Some diffs between in game text v this doc

### ISSUE THREAD

**Issue by spikerobinson** [iktools/Ancient-Star#40]
I believe what is called in-game "supplies" is here called "credits".

The tech effect descriptions here seem to be significantly different from what is stated in the in-game help.

Great job, great documwnt, thank you for your hard work!

**Comment by iktools** [comment]
Thanks Spike!

Credits should be supplies, good catch. Which tech effects differ between the design document and the game? I've noticed math stimulus bonus was not updated to addition but the rest is in line with the code. Maybe the wording is misleading?

Edit: speaking of wording quality, math stimulus bonus is indeed correctly listed.

**Comment by subchannel13** [comment]
Closed due to no more actionable comments.

**Comment by spikerobinson** [comment]
Ah maybe I am misunderstanding. In the design doc it is shown as a
formula.  In the game help it is shown as an example of the Level 1 values.
Is that correct?

**Comment by subchannel13** [comment]
Ah, now I understand what bothers you. What is shown is game are bonuses you currently have, at your current tech level. I thought about separating those values from tech field selection, say by listing them below or at the side, and showing next level benefits at tech selection.

**Comment by subchannel13** [comment]
The solution in v2.47 is not the prettiest one, you'll have to deal with it until I come around with something nicer.
